#!/bin/bash
echo "Injecting environment variables..."
cat > js/config.js << JSEOF
// =============================================
// js/config.js — Auto-generated by build.sh
// =============================================

const SUPABASE_URL = '${SUPABASE_URL}';
const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';

// Initialize Supabase client
const { createClient } = supabase;
const sb = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const CATEGORIES = [
  { id: 'nashta',      label: 'Nashta',        icon: '🍳', color: '#f59e0b' },
  { id: 'milk',        label: 'Milk',           icon: '🥛', color: '#06b6d4' },
  { id: 'petrol',      label: 'Petrol',         icon: '⛽', color: '#ef4444' },
  { id: 'grocery',     label: 'Grocery',        icon: '🛒', color: '#10b981' },
  { id: 'vegetables',  label: 'Vegetables',     icon: '🥦', color: '#84cc16' },
  { id: 'fruits',      label: 'Fruits',         icon: '🍎', color: '#f97316' },
  { id: 'utility',     label: 'Utility Bills',  icon: '💡', color: '#8b5cf6' },
  { id: 'snacks',      label: 'Cheez/Snacks',   icon: '🍿', color: '#ec4899' },
  { id: 'others',      label: 'Others',         icon: '📦', color: '#6b7280' },
];

function getCat(id) {
  return CATEGORIES.find(c => c.id === id) || CATEGORIES[CATEGORIES.length - 1];
}

function formatPKR(amount) {
  return 'Rs. ' + Number(amount).toLocaleString('en-PK', { minimumFractionDigits: 0 });
}

function formatDate(dateStr) {
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-PK', { day: 'numeric', month: 'short', year: 'numeric' });
}

function toYMD(date) {
  return date.toISOString().split('T')[0];
}

function currentYM() {
  const n = new Date();
  return \`\${n.getFullYear()}-\${String(n.getMonth()+1).padStart(2,'0')}\`;
}

function initials(name) {
  if (!name) return '?';
  return name.split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2);
}
JSEOF
echo "Done! config.js generated."
